unique_ids:
  assets:
    standard-page.html: 64LJGX7NQJZ6BOYAEIJIAD5CUZJRFBYD
    theme.css: XZYHICYYOV5TZU7KC6T7RRIZXBCRR36Q
  forms:
    Form1: 6CMQT4EZCVZ2BB4SHVJMCE3FSTGF6HJZ
  modules: {}
  scripts: {}
  server_modules: {}
